# -*- coding: utf-8 -*-
"""Pipeline de ETL com Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BdV5Sz7nsHE21Z-djLTerI-4GTvRPwa

**Contexto:** Você é um cientista de dados no Santander e recebeu a tarefa de envolver seus clientes de maneira mais personalizada. Seu objetivo é usar o poder da IA Generativa para criar mensagens de marketing personalizadas que serão entregues a cada cliente.

**Condições do Problema:**

1. Você recebeu uma planilha simples, em formato CSV ('SDW2026.csv'), com uma lista de IDs de usuário do banco:

```
UserID:
1
2
3
4
5
```

2. Seu trabalho é consumir o endpoint GET https://sdw-2023-prd.up.railway.app/users/{id} (API da Santander Dev Week 2023) para obter os dados de cada cliente.

3. Depois de obter os dados dos clientes, você vai usar a API do ChatGPT (OpenAI) para gerar uma mensagem de marketing personalizada para cada cliente. Essa mensagem deve enfatizar a importância dos investimentos.

4. Uma vez que a mensagem para cada cliente esteja pronta, você vai enviar essas informações de volta para a API, atualizando a lista de "news" de cada usuário usando o endpoint PUT https://sdw-2023-prd.up.railway.app/users/{id}.
"""

# Utilize sua própria URL se quiser ;)
# Repositório da API: https://github.com/digitalinnovationone/santander-dev-week-2023-api
import json
import subprocess
import requests
import pandas as pd
from google import genai
from google.genai import types

# URL do servidor local simulado
sdw2023_api_url = 'http://localhost:3000'

pip install -q "google-genai>=1.66.0,<2.0.0" "google-auth==2.47.0"
npm install -g json-server

# ==========================================
# 1. AMBIENTE & MOCK DA API
# ==========================================

# Criar o arquivo de dados simulados (db.json) com a estrutura oficial
mock_data = {
    "users": [
        {
            "id": 4,
            "name": "Devweek User 4",
            "account": { "id": 4, "number": "00004-4", "agency": "0004", "balance": 1000.0, "limit": 500.0 },
            "card": { "id": 4, "number": "xxxx xxxx xxxx 4444", "limit": 2000.0 },
            "features": [],
            "news": []
        },
        {
            "id": 5,
            "name": "Devweek User 5",
            "account": { "id": 5, "number": "00005-5", "agency": "0005", "balance": 2500.0, "limit": 1000.0 },
            "card": { "id": 5, "number": "xxxx xxxx xxxx 5555", "limit": 5000.0 },
            "features": [],
            "news": []
        },
        {
            "id": 6,
            "name": "Devweek User 6",
            "account": { "id": 6, "number": "00006-6", "agency": "0006", "balance": 500.0, "limit": 200.0 },
            "card": { "id": 6, "number": "xxxx xxxx xxxx 6666", "limit": 1000.0 },
            "features": [],
            "news": []
        }
    ]
}

with open('db.json', 'w') as f:
    json.dump(mock_data, f, indent=2)

# Iniciar o json-server em segundo plano na porta 3000
subprocess.Popen(["json-server", "--watch", "db.json", "--port", "3000"])

# Documentação Oficial da API OpenAI: https://platform.openai.com/docs/api-reference/introduction
# Informações sobre o Período Gratuito: https://help.openai.com/en/articles/4936830

# Para gerar uma API Key:
# 1. Crie uma conta na GoogleAIStudio
# 2. Acesse a seção "API Keys"
# 3. Clique em "Create API Key"
# Link direto: https://aistudio.google.com/api-keys?project=gen-lang-client-0871136811

# ==========================================
# 2. CONFIGURAÇÃO DO CLIENTE GEMINI
# ==========================================

# TODO: Substitua obrigatoriamente pelo seu token real do Google AI Studio
gemini_api_key = 'AIzaSyAkm5860A33hi2Cfp4gNvlDa5M2wcKbsuY'

# Inicializa o cliente oficial do ecossistema Google
client = genai.Client(api_key=gemini_api_key)

"""###Extract

Extraia a lista de IDs de usuário a partir do arquivo CSV. Para cada ID, faça uma requisição GET para obter os dados do usuário correspondente.
"""

# --- EXTRACT (Extração) ---
df = pd.read_csv('SDW2026.csv')
user_ids = df['UserID:'].tolist()

def get_user(id):
    try:
        response = requests.get(f'{sdw2023_api_url}/users/{id}')
        return response.json() if response.status_code == 200 else None
    except requests.exceptions.ConnectionError:
        return None

# Coleta os dados dos usuários válidos encontrados no servidor local
users = [user for user_id in user_ids if (user := get_user(user_id)) is not None]

"""##Transform

Utilize a API do OpenAI GPT-4 para gerar uma mensagem de marketing personalizada para cada usuário.
"""

# --- TRANSFORM (Transformação com IA) ---
def generate_ai_news(user):
    config = types.GenerateContentConfig(
        system_instruction="Você é um especialista em marketing bancário."
    )

    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)",
        config=config
    )

    return response.text.strip('"').strip()

# Iteração para gerar o conteúdo e anexar à estrutura do usuário

for user in users:
    news_content = generate_ai_news(user)
    print(f"Mensagem gerada para {user['name']}: {news_content}")

    # Adiciona a nova mensagem gerada à lista 'news' do usuário

    user['news'].append({
        "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
        "description": news_content
    })

"""## Load

Atualize a lista de "news" de cada usuário na API com a nova mensagem gerada.
"""

def update_user(user):
    # Envia os dados atualizados com a nova mensagem de volta para a API
    response = requests.put(f'{sdw2023_api_url}/users/{user["id"]}', json=user)
    return True if response.status_code == 200 else False

print("\n--- Atualizando banco de dados simulado (Load) ---")
for user in users:
    success = update_user(user)
    status = "Sucesso" if success else "Falha"
    print(f"Atualização do usuário {user['id']}: {status}")