# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "100"},
  "node01" => {"memory" => "512",  "cpu" => "1", "ip" => "101"},
  "node02" => {"memory" => "512",  "cpu" => "1", "ip" => "102"}
}

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "ubuntu/focal64"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"

      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.gui = false
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
      end

      machine.vm.provision "shell", path: "docker.sh"

      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end

    end
  end
end

